In [ ]:
#TODO
# commenter le code 
# split train/test/valid
# gerer le désquilibre entre delay et pas delay 
# trouver une meilleure méthode de sélection de features
# comparaison de modèles 
# ajouter des variables

In [17]:
import os
import json 
import psycopg2
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.types import String, Date, DateTime
from sqlalchemy import text
import re

In [2]:
def connect_to_postgre(db_uri):
    # Connect to local postgre instance for dev 
    conn = psycopg2.connect(db_uri)
    cur = conn.cursor()
    engine = create_engine(db_uri)
    return conn, cur, engine
db_uri =  f"postgresql://pierre:data@localhost:5432/dst_db"
conn, cur, engine = connect_to_postgre(db_uri)

In [3]:
sql = text(
    '''
WITH
departures AS (
    SELECT
        fl."departureAirportCode",
        sf."flightScheduleDate",
        COUNT(DISTINCT fl."flightLegId") AS "nbFlightDeparting"
    FROM
        "flightLeg" fl
    LEFT JOIN
        "scheduledFlight" sf ON fl."scheduledFlightId" = sf."scheduledFlightId"
    GROUP BY
        fl."departureAirportCode", sf."flightScheduleDate"
),
arrivals AS (
    SELECT
        fl."arrivalAirportCode",
        SUBSTR(fl."arrivalScheduledTime", 1, 10) AS "arrivalScheduledDate",
        COUNT(DISTINCT fl."flightLegId") AS "nbFlightArriving"
    FROM
        "flightLeg" fl
    GROUP BY
        fl."arrivalAirportCode", SUBSTR(fl."arrivalScheduledTime", 1, 10)
)
SELECT
    d."departureAirportCode",
    d."flightScheduleDate",
    d."nbFlightDeparting",
    a."nbFlightArriving"
FROM
    departures d
INNER JOIN
    arrivals a ON d."departureAirportCode" = a."arrivalAirportCode"
              AND d."flightScheduleDate" = a."arrivalScheduledDate";
;
     
    '''
)
agg = pd.read_sql(sql, engine)
agg.head()
# on merge cette aggregation en deux fois: une fois avec le departureAirport et une fois avec le arrival, en modifiant les noms de colonnes pour indiquer où ça s'applique

  departureAirportCode flightScheduleDate  nbFlightDeparting  nbFlightArriving
0                  AAE         2026-01-01                  1                 2
1                  AAE         2026-01-02                  1                 1
2                  AAE         2026-01-08                  1                 2
3                  AAE         2026-01-09                  1                 1
4                  AAE         2026-01-11                  1                 2

In [4]:
sql = text(
    '''
    
    SELECT  fl."flightLegId",fl."scheduledFlightId",sf."flightNumber",sf."flightScheduleDate",
    fl."departureScheduledTime",fl."arrivalScheduledTime",fl."departureActualTime", 
    fl."arrivalActualTime",         SUBSTR(fl."arrivalScheduledTime", 1, 10) AS "arrivalScheduledDate",
    SUBSTR(sf."flightScheduleDate", 9, 2) AS "departureMonthDay",
     fl."scheduledFlightDuration", fl."aircraftCode",sf."airlineCode",
     fl."departureAirportCode",fl."arrivalAirportCode",i."delayDuration" 
     
     from "flightLeg" fl 
    left join "scheduledFlight" sf on fl."scheduledFlightId" = sf."scheduledFlightId"
    left join "irregularity" i on fl."flightLegId" = i."flightLegId"

    ;
     
    '''
)
df = pd.read_sql(sql, engine)

In [5]:
df.head()

,flightLegId,scheduledFlightId,flightNumber,flightScheduleDate,departureScheduledTime,arrivalScheduledTime,departureActualTime,arrivalActualTime,arrivalScheduledDate,departureMonthDay,scheduledFlightDuration,aircraftCode,airlineCode,departureAirportCode,arrivalAirportCode,delayDuration
0,20260109+DL+0893+DFW+ATL,20260109+DL+0893,893,2026-01-09,2026-01-09T07:00:00.000-06:00,2026-01-09T10:11:00.000-05:00,None,None,2026-01-09,09,PT2H11M,320,DL,DFW,ATL,00
1,20260109+DL+1236+MKE+ATL,20260109+DL+1236,1236,2026-01-09,2026-01-09T07:00:00.000-06:00,2026-01-09T10:14:00.000-05:00,2026-01-09T06:53:00.000-06:00,2026-01-09T09:49:00.000-05:00,2026-01-09,09,PT2H14M,738,DL,MKE,ATL,00
2,20260109+DL+1258+AUS+ATL,20260109+DL+1258,1258,2026-01-09,2026-01-09T07:00:00.000-06:00,2026-01-09T10:14:00.000-05:00,None,None,2026-01-09,09,PT2H14M,321,DL,AUS,ATL,00
3,20260109+DL+1311+ATL+PBI,20260109+DL+1311,1311,2026-01-09,2026-01-09T08:00:00.000-05:00,2026-01-09T09:54:00.000-05:00,2026-01-09T07:55:00.000-05:00,2026-01-09T09:31:00.000-05:00,2026-01-09,09,PT1H54M,321,DL,ATL,PBI,00
4,20260109+DL+1311+PBI+ATL,20260109+DL+1311,1311,2026-01-09,2026-01-09T11:00:00.000-05:00,2026-01-09T12:54:00.000-05:00,2026-01-09T11:09:00.000-05:00,2026-01-09T13:11:00.000-05:00,2026-01-09,09,PT1H54M,321,DL,PBI,ATL,00

In [6]:
# Merge aggregation
print(df.shape)
df = df.merge(agg,how='left', on=["departureAirportCode","flightScheduleDate"])
print(df.shape)
df = df.merge(agg,how='left', left_on=["arrivalAirportCode","arrivalScheduledDate"], right_on=["departureAirportCode","flightScheduleDate"] , 
suffixes=('',"ArrivalAirport"))
print(df.shape)
del df["departureAirportCodeArrivalAirport"]
del df["flightScheduleDateArrivalAirport"]
df = df.rename(columns={"nbFlightDeparting": "nbFlightDepartingDepartureAirport", "nbFlightArriving": "nbFlightArrivingDepartureAirport"})

#nbFlightArrivingDepartureAirport : variable obtenue par agrégation qui compte le nombre de vols qui atterrissent à l'aéroport de départ le même jour que le flightLeg
#nbFlightDepartingDepartureAirport: variable obtenue par agrégation qui compte le nombre de vols qui décollent de l'aéroport de départ le même jour que le flightLeg
#nbFlightArrivingArrivalAirport:  variable obtenue par agrégation qui compte le nombre de vols qui atterrissent à l'aéroport d'arrivée le même jour que le flightLeg
#nbFlightDepartingArrivalAirport: variable obtenue par agrégation qui compte le nombre de vols qui décollent de l'aéroport d'arrivée le même jour que le flightLeg

(259649, 16)
(259649, 18)
(259649, 22)

In [77]:
df.head()

,flightLegId,scheduledFlightId,flightNumber,flightScheduleDate,departureScheduledTime,arrivalScheduledTime,departureActualTime,arrivalActualTime,arrivalScheduledDate,scheduledFlightDuration,aircraftCode,airlineCode,departureAirportCode,arrivalAirportCode,delayDuration,nbFlightDeparting,nbFlightArriving,nbFlightDepartingArrivalAirport,nbFlightArrivingArrivalAirport
0,20260130+MF+8468+KWE+HGH,20260130+MF+8468,8468,2026-01-30,2026-01-30T19:00:00.000+08:00,2026-01-30T21:25:00.000+08:00,None,None,2026-01-30,PT2H25M,738,MF,KWE,HGH,00,7.0,7.0,22.0,29.0
1,20260130+MF+8468+KWE+HGH,20260130+MF+8468,8468,2026-01-30,2026-01-30T19:00:00.000+08:00,2026-01-30T21:25:00.000+08:00,None,None,2026-01-30,PT2H25M,738,MF,KWE,HGH,00,7.0,7.0,22.0,29.0
2,20260130+MF+8650+BKI+FOC,20260130+MF+8650,8650,2026-01-30,2026-01-30T19:00:00.000+08:00,2026-01-30T22:50:00.000+08:00,None,None,2026-01-30,PT3H50M,738,MF,BKI,FOC,00,2.0,3.0,28.0,36.0
3,20260130+MF+8650+BKI+FOC,20260130+MF+8650,8650,2026-01-30,2026-01-30T19:00:00.000+08:00,2026-01-30T22:50:00.000+08:00,None,None,2026-01-30,PT3H50M,738,MF,BKI,FOC,00,2.0,3.0,28.0,36.0
4,20260130+MU+2232+PVG+XIY,20260130+MU+2232,2232,2026-01-30,2026-01-30T21:00:00.000+08:00,2026-01-30T23:35:00.000+08:00,None,None,2026-01-30,PT2H35M,319,MU,PVG,XIY,00,119.0,117.0,43.0,53.0

In [7]:
# Get weekday
import datetime 

def get_week_day(date):
    y = int(date[0:4])
    m = int(date[5:7])
    d = int(date[8:10])
    return datetime.datetime(y,m,d).weekday()


df.insert( df.shape[1], "departureWeekDay", df["flightScheduleDate"].apply(lambda x: get_week_day(x))) # ajoute la variable à prédire

In [8]:
# Get hour and month 
df.insert( df.shape[1], "departureMonth", df["flightScheduleDate"].apply(lambda x: int(x[5:7]))) # ajoute la variable à prédire 
df.insert( df.shape[1], "departureHour", df["departureScheduledTime"].apply(lambda x: int(x[14:16]))) # ajoute la variable à prédire

In [9]:
# Prepated predicted variable 
df.delayDuration = df.delayDuration.astype(int)
df.delayDuration.loc[df.delayDuration!="00"].describe() # en minutes 
df.insert( df.shape[1], "is_delayed", (df.delayDuration>=15).astype(int)) # ajoute la variable à prédire

In [33]:
features = ['scheduledFlightDuration', 
       'aircraftCode',
       'airlineCode', 
       'departureAirportCode', 
       'arrivalAirportCode',
       'departureMonthDay',
       'departureWeekDay',
        'departureMonth',
       'departureHour']
y_duration =  ["delayDuration"]
y_delay = ["is_delayed"]
df_features = df[features + y_duration + y_delay]
df_features.index = df['flightLegId']

In [35]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259649 entries, 20260109+DL+0893+DFW+ATL to 20260109+DL+1646+ATL+DTW
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   scheduledFlightDuration  253456 non-null  object
 1   aircraftCode             259646 non-null  object
 2   airlineCode              259649 non-null  object
 3   departureAirportCode     259649 non-null  object
 4   arrivalAirportCode       259649 non-null  object
 5   departureMonthDay        259649 non-null  object
 6   departureWeekDay         259649 non-null  int64
 7   departureMonth           259649 non-null  int64
 8   departureHour            259649 non-null  int64
 9   delayDuration            259649 non-null  int64
 10  is_delayed               259649 non-null  int64
dtypes: int64(5), object(6)
memory usage: 23.8+ MB

In [36]:
# Calculate the proportion of missing data

def checkMissing(data,perc=0):
    """ 
    Takes in a dataframe and returns
    the percentage of missing value.
    """
    missing = [(i, data[i].isna().mean()*100) for i in data]
    missing = pd.DataFrame(missing, columns=["column_name", "percentage"])
    missing = missing[missing.percentage > perc]
    print(missing.sort_values("percentage", ascending=False).reset_index(drop=True))

print("Proportion of missing data in columns")
checkMissing(df_features)

Proportion of missing data in columns
               column_name  percentage
0  scheduledFlightDuration    2.385143
1             aircraftCode    0.001155

In [37]:
df_features = df_features.loc[-df_features.scheduledFlightDuration.isna()]
checkMissing(df_features)

Empty DataFrame
Columns: [column_name, percentage]
Index: []

In [38]:
def parse_flight_duration(flightDuration: str):
    hours_ =  re.findall(r"(\d{1,2})H", flightDuration)
    minutes_ = re.findall(r"(\d{1,2})M", flightDuration)
    if len(hours_)>0:
        hours_ = int(hours_[0])
    else :
        hours_ = 0
    if len(minutes_)>0:
        minutes_ = int(minutes_[0])
    else :
        minutes_ = 0 
    return hours_*60 + minutes_

In [39]:
df_features["scheduledFlightDuration"] = df_features.scheduledFlightDuration.apply(lambda x: parse_flight_duration(x))

In [40]:
df_features.departureMonthDay = df_features.departureMonthDay.astype(int)

In [41]:
#categorical data
categorical_cols = ['aircraftCode', 'airlineCode', 'departureAirportCode', 'arrivalAirportCode'] 
for col in categorical_cols:
    print(col +":"+str(len(df_features[col].unique())))
# On retire les aéroports des variables. Le nombre de vols qui arrivent et repartent sont des proxy
categorical_cols = ['aircraftCode', 'airlineCode'] 
df_features = pd.get_dummies(df_features, columns = categorical_cols, dtype=float, drop_first=True)

aircraftCode:97
airlineCode:149
departureAirportCode:1080
arrivalAirportCode:1075

In [42]:
del df_features['departureAirportCode']
del df_features['arrivalAirportCode']

In [43]:
df_features.columns

Index(['scheduledFlightDuration', 'departureMonthDay', 'departureWeekDay',
       'departureMonth', 'departureHour', 'delayDuration', 'is_delayed',
       'aircraftCode_220', 'aircraftCode_221', 'aircraftCode_223',
       ...
       'airlineCode_WB', 'airlineCode_WF', 'airlineCode_WM', 'airlineCode_WS',
       'airlineCode_WY', 'airlineCode_XG', 'airlineCode_XK', 'airlineCode_XQ',
       'airlineCode_YY', 'airlineCode_ZT'],
      dtype='object', length=251)

In [48]:
X = df_features.loc[:, df_features.columns != 'is_delayed']
X = X.loc[:, X.columns != 'delayDuration']
y_duration =  df_features["delayDuration"]
y_delay = df_features["is_delayed"]

In [56]:
# Normalize 
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
print(scaler.fit(X))
X_norm = scaler.transform(X)

MinMaxScaler()

In [60]:
# Feature selection 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

X_new = SelectKBest(f_classif, k=20).fit_transform(X_norm, y_delay)

In [62]:
X_new

array([[0.1230916 , 0.26666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.1259542 , 0.26666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.1259542 , 0.26666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.10782443, 0.26666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.10591603, 0.26666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.11354962, 0.26666667, 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(253456, 20))